Repository GAMZA-BAT/algohub-server, pull requests merged in 2024-09, with the labels that each got.

#87 feat : 이메일 중복 검사 API 추가
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/CheckEmailRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: new-feature

#92 feat : 멤버 role 수정 API 추가
  src/main/java/com/gamzabat/algohub/common/annotation/EnumValidator.java
  src/main/java/com/gamzabat/algohub/common/annotation/ValidEnum.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/domain/GroupMember.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/UpdateGroupMemberRoleRequest.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature

#97 feat : 닉네임 중복 검사 API 추가
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/CheckNicknameValidationException.java
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: new-feature

#95 feat : 그룹 목록 조회 API에서 즐겨찾기 여부 추가
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetStudyGroupResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/BookmarkedStudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature, self-merge

#98 feat : 문제 기간 수정 시, 이미 시작 날짜가 지난 문제는 시작 날짜 수정 막는 로직 추가
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/test/java/com/gamzabat/algohub/feature/problem/controller/ProblemControllerTest.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
Labels: new-feature

#101 refactor : 이메일 중복 검사 메소드 중복 제거
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: refactoring

#99 feat:공지 목록 조회API 추가
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
  src/main/java/com/gamzabat/algohub/feature/board/repository/BoardRepository.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
Labels: new-feature

#83 feat : 문제 별 풀이 검색 API 추가
  src/main/java/com/gamzabat/algohub/constants/ApiConstants.java
  src/main/java/com/gamzabat/algohub/constants/LanguageConstants.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/solution/controller/SolutionControllerTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: new-feature

#105 refactor : GroupMember role에 OWNER 추가
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/domain/StudyGroup.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetStudyGroupResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/etc/RoleOfGroupMember.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/GroupMemberRepository.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/querydsl/CustomStudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/querydsl/CustomStudyGroupRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
  src/test/java/com/gamzabat/algohub/feature/problem/controller/ProblemControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
  src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: refactoring

#106 refactor : BOJResultConstants 추가 및 리팩토링
  src/main/java/com/gamzabat/algohub/constants/BOJResultConstants.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: refactoring

#107 feat : 그룹 회원 목록 조회 API isOwner -> role로 수정
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetGroupMemberResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature, refactoring

#109 fix : 그룹 목록 조회 시 주인이어도 isOwner가 false로 발생하는 버그 수정
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetStudyGroupResponse.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: bug

#113 fix : Solution content 필드를 varchar(255) -> TEXT로 수정
  src/main/java/com/gamzabat/algohub/feature/solution/domain/Solution.java
Labels: bug
