Repository GAMZA-BAT/algohub-server, pull requests merged in 2024-10, with the labels that each got.

#124 refactor : 회원가입 API 엔드포인트 /register -> /sign-up 변경
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
Labels: trivial

#121 feat : 날짜 포매터 전역 적용
  src/main/java/com/gamzabat/algohub/common/DateFormatUtil.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardResponse.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/main/java/com/gamzabat/algohub/feature/comment/dto/GetCommentResponse.java
  src/main/java/com/gamzabat/algohub/feature/notification/dto/GetNotificationResponse.java
  src/main/java/com/gamzabat/algohub/feature/problem/dto/GetProblemResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetSolutionResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetGroupMemberResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetGroupResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetStudyGroupResponse.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
  src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature

#128 refactor : API return 타입 리팩토링
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
  src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
  src/main/java/com/gamzabat/algohub/feature/problem/controller/ProblemController.java
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GroupCodeResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/test/java/com/gamzabat/algohub/feature/problem/controller/ProblemControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
Labels: refactoring

#133 feat : 문제 생성 시의 알림 로직 제거 및 문제 시작 시 알림 전송 추가
  src/main/java/com/gamzabat/algohub/AlgohubApplication.java
  src/main/java/com/gamzabat/algohub/feature/notification/enums/NotificationMessage.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
Labels: new-feature

#117 feat:공지 수정 API
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
  src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/UpdateBoardRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
Labels: new-feature

#132 refactor : Bookmark가 코드로 관리되는 타입을 리턴하도록 변경
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/BookmarkStatus.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/UpdateBookmarkResponse.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: refactoring
