Repository GAMZA-BAT/algohub-server, pull requests merged in 2024-11, with the labels that each got.

#142 feat: 공지 댓글 기능 구현
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardCommentController.java
  src/main/java/com/gamzabat/algohub/feature/board/domain/BoardComment.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/repository/BoardCommentRepository.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardCommentService.java
  src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
  src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
  src/main/java/com/gamzabat/algohub/feature/comment/dto/CreateCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/comment/dto/GetCommentResponse.java
  src/main/java/com/gamzabat/algohub/feature/comment/repository/CommentRepository.java
  src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionCommentController.java
  src/main/java/com/gamzabat/algohub/feature/solution/domain/SolutionComment.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/CreateSolutionCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/solution/exception/SolutionValidationException.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionCommentRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionCommentService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/feature/board/service/BoardCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/feature/solution/controller/SolutionControllerTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: new-feature, refactoring

#138 refactor : 문제 풀이 결과 형태 수정
  src/main/java/com/gamzabat/algohub/constants/BOJResultConstants.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetSolutionResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: refactoring

#147 feat : Implement board delete API
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
  src/main/java/com/gamzabat/algohub/feature/board/exception/BoardValidationException.java
  src/main/java/com/gamzabat/algohub/feature/board/repository/BoardCommentRepository.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardCommentService.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/test/java/com/gamzabat/algohub/feature/board/service/BoardCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
Labels: new-feature

#144 feat : 스터디 그룹 공개 여부 설정 API 추가
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/domain/GroupMember.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/EditGroupVisibilityRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/GetStudyGroupResponse.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature, refactoring

#148 refactor : rename board to notice
  build.gradle
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardResponse.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/UpdateBoardRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/exception/BoardValidationException.java
  src/main/java/com/gamzabat/algohub/feature/board/repository/BoardCommentRepository.java
  src/main/java/com/gamzabat/algohub/feature/board/repository/BoardRepository.java
  src/main/java/com/gamzabat/algohub/feature/notice/controller/NoticeCommentController.java
  src/main/java/com/gamzabat/algohub/feature/notice/controller/NoticeController.java
  src/main/java/com/gamzabat/algohub/feature/notice/domain/Notice.java
  src/main/java/com/gamzabat/algohub/feature/notice/domain/NoticeComment.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/CreateNoticeCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/CreateNoticeRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/GetNoticeResponse.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/UpdateNoticeRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/exception/NoticeValidationException.java
  src/main/java/com/gamzabat/algohub/feature/notice/repository/NoticeCommentRepository.java
  src/main/java/com/gamzabat/algohub/feature/notice/repository/NoticeRepository.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeCommentService.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/feature/notice/service/NoticeCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: refactoring

#140 feat : 설정 따른 알림 전송
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/notification/controller/NotificationController.java
  src/main/java/com/gamzabat/algohub/feature/notification/domain/NotificationSetting.java
  src/main/java/com/gamzabat/algohub/feature/notification/dto/EditNotificationSettingRequest.java
  src/main/java/com/gamzabat/algohub/feature/notification/dto/GetNotificationSettingResponse.java
  src/main/java/com/gamzabat/algohub/feature/notification/enums/NotificationCategory.java
  src/main/java/com/gamzabat/algohub/feature/notification/enums/NotificationMessage.java
  src/main/java/com/gamzabat/algohub/feature/notification/exception/CannotFoundNotificationSettingException.java
  src/main/java/com/gamzabat/algohub/feature/notification/repository/NotificationSettingRepository.java
  src/main/java/com/gamzabat/algohub/feature/notification/repository/querydsl/CustomNotificationSettingRepository.java
  src/main/java/com/gamzabat/algohub/feature/notification/repository/querydsl/CustomNotificationSettingRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/notification/service/NotificationService.java
  src/main/java/com/gamzabat/algohub/feature/notification/service/NotificationSettingService.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionCommentService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/feature/group/ranking/service/RankingUpdateServiceAOPTest.java
  src/test/java/com/gamzabat/algohub/feature/notification/service/NotificationSettingServiceTest.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature, self-merge

#150 feat: Add category to notice
  src/main/java/com/gamzabat/algohub/feature/notice/domain/Notice.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/CreateNoticeRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/GetNoticeResponse.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/UpdateNoticeRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: new-feature

#156 feat : 나의 풀이 목록 조회 API 추가
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/feature/solution/controller/SolutionControllerTest.java
Labels: new-feature

#151 feat : 공지 읽음 표시 로직 추가 및 response 수정
  src/main/java/com/gamzabat/algohub/feature/notice/domain/NoticeRead.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/GetNoticeResponse.java
  src/main/java/com/gamzabat/algohub/feature/notice/repository/NoticeReadRepository.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: new-feature, self-merge

#159 refactor:notice 날짜 포맷팅 수정
  src/main/java/com/gamzabat/algohub/common/DateFormatUtil.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/GetNoticeResponse.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: refactoring

#162 refactor : StudyGroupController 관련 API 엔드포인트 수정
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/EditGroupRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/EditGroupVisibilityRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/UpdateGroupMemberRoleRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: refactoring

#164 refactor : UserController 관련 API 엔드포인트 수정
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
Labels: refactoring

#178 feat : 스터디 그룹 코드로 조회 시 방장 닉네임 추가
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/GetStudyGroupWithCodeResponse.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
Labels: new-feature

#176 refactor : NotificationController 관련 API 엔드포인트 수정
  src/main/java/com/gamzabat/algohub/feature/notification/controller/NotificationController.java
Labels: refactoring

#174 refactor : RankingController 관련 API 엔드포인트 수정 및 top-ranking 제거
  src/main/java/com/gamzabat/algohub/feature/group/ranking/controller/RankingController.java
  src/main/java/com/gamzabat/algohub/feature/group/ranking/service/RankingService.java
  src/test/java/com/gamzabat/algohub/feature/group/ranking/controller/RankingControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/group/ranking/service/RankingServiceTest.java
Labels: refactoring

#172 refactor : NoticeController 관련 API 엔드포인트 수정
  src/main/java/com/gamzabat/algohub/feature/notice/controller/NoticeController.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/CreateNoticeRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/UpdateNoticeRequest.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: refactoring

#166 refactor : ProblemController 관련 API 엔드포인트 수정
  src/main/java/com/gamzabat/algohub/feature/problem/controller/ProblemController.java
  src/main/java/com/gamzabat/algohub/feature/problem/dto/CreateProblemRequest.java
  src/main/java/com/gamzabat/algohub/feature/problem/dto/EditProblemRequest.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/test/java/com/gamzabat/algohub/feature/problem/controller/ProblemControllerTest.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
Labels: refactoring

#182 fix : 문제 삭제 시 soft delete 오류 해결
  src/main/java/com/gamzabat/algohub/feature/problem/domain/Problem.java
Labels: bug

#184 fix : JwtAuthenticationFilter 제외 endpoint 수정
  src/main/java/com/gamzabat/algohub/common/jwt/JwtAuthenticationFilter.java
Labels: bug

#186 feat : 공지, 랭킹 목록 조회 페이징 적용 및 잡다한 것들
  src/main/java/com/gamzabat/algohub/feature/group/ranking/controller/RankingController.java
  src/main/java/com/gamzabat/algohub/feature/group/ranking/dto/GetRankingResponse.java
  src/main/java/com/gamzabat/algohub/feature/group/ranking/repository/querydsl/CustomRankingRepository.java
  src/main/java/com/gamzabat/algohub/feature/group/ranking/repository/querydsl/CustomRankingRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/group/ranking/service/RankingService.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/notice/controller/NoticeController.java
  src/main/java/com/gamzabat/algohub/feature/notice/dto/GetNoticeResponse.java
  src/main/java/com/gamzabat/algohub/feature/notice/repository/NoticeRepository.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/feature/group/ranking/controller/RankingControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/group/ranking/service/RankingServiceTest.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: new-feature, self-merge

#190 feat : 문제 생성 시 잘못된 링크 예외 조건 추가
  src/main/java/com/gamzabat/algohub/constants/ApiConstants.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
Labels: new-feature

#192 feat : 알림 단건 읽음 표시 API 추가
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/notification/controller/NotificationController.java
  src/main/java/com/gamzabat/algohub/feature/notification/exception/CannotFoundNotificationException.java
  src/main/java/com/gamzabat/algohub/feature/notification/exception/NotificationValidationException.java
  src/main/java/com/gamzabat/algohub/feature/notification/service/NotificationService.java
  src/test/java/com/gamzabat/algohub/feature/notification/service/NotificationServiceTest.java
Labels: new-feature

#197 feat : 정확도, 제출한 사람 수, 전체 멤버 수 GetSolutionResponse에 추가
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetSolutionResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetSolutionWithGroupIdResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
Labels: new-feature

#199 refactor : 스터디 그룹 목록 조회 시 날짜 정보 Date 타입으로 수정
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/GetGroupResponse.java
Labels: refactoring

#203 refactor : 타유저 그룹 목록 조회 시 path variable 수정
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: refactoring

#204 refactor : 공지 목록 조회 시 최신순 정렬
  src/main/java/com/gamzabat/algohub/feature/notice/controller/NoticeController.java
  src/test/java/com/gamzabat/algohub/service/NoticeServiceTest.java
Labels: refactoring

#207 refactor : 타 유저 정보 조회 시 닉네임으로 수정
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: refactoring

#208 refactor : 내 풀이 목록 조회 API 기간 별 그룹화 추가
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetMySolutionListResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetMySolutionListWithGroupIdResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/enums/ProgressCategory.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: new-feature, refactoring

#210 feat : 문제 단건 조회 API 추가
  src/main/java/com/gamzabat/algohub/feature/problem/controller/ProblemController.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
Labels: new-feature

#216 feat : 내 풀이 목록 기간 별 api 분리
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetMySolutionListWithGroupIdResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: new-feature

#218 fix : 공지 삭제 시 오류 해결
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/notice/repository/NoticeReadRepository.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: bug

#220 fix : 댓글 생성 시 생성 날짜 로직 수정
  src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
  src/main/java/com/gamzabat/algohub/feature/notice/domain/NoticeComment.java
  src/main/java/com/gamzabat/algohub/feature/solution/domain/SolutionComment.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionCommentService.java
  src/test/java/com/gamzabat/algohub/feature/notice/service/NoticeCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionCommentServiceTest.java
Labels: bug

#223 refactor : 문제 목록 마감기간 기준 최신순 정렬
  src/main/java/com/gamzabat/algohub/feature/problem/controller/ProblemController.java
  src/test/java/com/gamzabat/algohub/feature/problem/controller/ProblemControllerTest.java
Labels: refactoring
