Repository GAMZA-BAT/algohub-server, pull requests merged in 2024-08, with the labels that each got.

#22 feat: CI/CD 구축
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
Labels: enhancement

#17 [#16] feat : 그룸 멤버 전체 랭킹 API 추가
  src/main/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
Labels: new-feature

#25 feat/댓글 수정API 추가
  src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
  src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
  src/main/java/com/gamzabat/algohub/feature/comment/dto/ModifyCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
Labels: new-feature

#31 refactor: 마감 문제 조회를 내일까지 수정
  src/main/java/com/gamzabat/algohub/feature/problem/controller/ProblemController.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
Labels: refactoring

#27 feat : CI/CD 후속작업
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
Labels: enhancement

#43 refactor : 풀이 조회 관련 API 엔드포인트 수정
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/solution/exception/CannotFoundSolutionException.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/feature/solution/controller/SolutionControllerTest.java
Labels: trivial

#36 feat : 문제 풀이 결과 세분화
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/domain/Solution.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetSolutionResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: new-feature

#48 feat : 스터디 그룹 즐겨찾기 추가/취소 API 추가
  src/main/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/domain/BookmarkedStudyGroup.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/BookmarkedStudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature

#59 feat : 스터디 그룹 목록 조회 API에서 즐겨찾기 카테고리 추가
  src/main/java/com/gamzabat/algohub/feature/studygroup/dto/GetStudyGroupListsResponse.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/BookmarkedStudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature

#50 test:댓글API 테스트 작성
  src/main/java/com/gamzabat/algohub/feature/comment/controller/CommentController.java
  src/main/java/com/gamzabat/algohub/feature/comment/domain/Comment.java
  src/main/java/com/gamzabat/algohub/feature/comment/dto/UpdateCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/comment/service/CommentService.java
  src/test/java/com/gamzabat/algohub/service/CommentServiceTest.java
Labels: test

#68 fix : 즐겨찾기 된 스터디 그룹 삭제 시 즐겨찾기도 삭제 안됨 오류 수정
  src/main/java/com/gamzabat/algohub/feature/studygroup/repository/BookmarkedStudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: bug

#66 fix : 스터디 그룹 목록 조회 시, InProgress 필터링 오류 수정
  src/main/java/com/gamzabat/algohub/feature/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: bug, self-merge

#69 feat:공지 작성 API 추가 했습니다
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
  src/main/java/com/gamzabat/algohub/feature/board/domain/Board.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/CreateBoardRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/repository/BoardRepository.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
Labels: new-feature

#73 feat : 백준 닉네임 유효성 검증 API 추가
  src/main/java/com/gamzabat/algohub/config/RestTemplateConfig.java
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/domain/User.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/BOJServerErrorException.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/CheckBjNicknameValidationException.java
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: new-feature

#75 test : UserService 테스트 작성
  src/main/java/com/gamzabat/algohub/feature/user/dto/CreateSolutionRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/UpdateUserRequest.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: test

#80 refactor : 문제 생성 API RestTemplate DI로 수정
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
Labels: refactoring

#82 refactor : URL 파일 분리
  src/main/java/com/gamzabat/algohub/common/ApiConstants.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
Labels: refactoring

#84 feat:공지 하나 조회 API 추가 및 submission.json 제거 및 refactor : 공지 등록 API 버그 수정...
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/board/controller/BoardController.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardRequest.java
  src/main/java/com/gamzabat/algohub/feature/board/dto/GetBoardResponse.java
  src/main/java/com/gamzabat/algohub/feature/board/exception/BoardValidationExceoption.java
  src/main/java/com/gamzabat/algohub/feature/board/service/BoardService.java
  src/test/java/com/gamzabat/algohub/service/BoardServiceTest.java
  submissions.json
Labels: bug, new-feature, refactoring

#85 refactor : 문제 생성 API에서 solved.ac API 호출 한 번으로 수정 및 에러처리 추가
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/problem/exception/SolvedAcApiErrorException.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/test/java/com/gamzabat/algohub/feature/problem/controller/ProblemControllerTest.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
Labels: refactoring
