Repository GAMZA-BAT/algohub-server, pull requests merged in 2025-04, with the labels that each got.

#365 feat: 소셜 로그인 회원 탈퇴
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/DeleteUserRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/UserInfoResponse.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: new-feature

#366 refactor:git 인코딩 이슈 해결
  src/main/java/com/gamzabat/algohub/auth/service/OAuth2Service.java
Labels: refactoring

#367 refactor : 공지 단건 조회시 image같이 전달
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
Labels: refactoring

#338 trivial:유의미한 데이터를 log 로 남기기
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeCommentService.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/main/java/com/gamzabat/algohub/feature/notification/service/NotificationService.java
  src/main/java/com/gamzabat/algohub/feature/notification/service/NotificationSettingService.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionCommentService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
Labels: trivial

#368 fix : OAuth 회원 탈퇴 로직 수정
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/DeleteUserRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/InvalidDeleteUserRequestException.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: bug

#369 (BE-14) refactor : 그룹 정보 수정
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/domain/StudyGroup.java
Labels: refactoring

#371 (BE-11) fix: Fix email html template
  src/main/resources/templates/email-template.html
Labels: bug

#372 fix: 회원 이메일 존재 오류 수정
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
Labels: bug

#370 refactor:백준 아이디 PATCH -> POST 수정
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
Labels: refactoring

#376 refactor: 댓글 및 공지 생성 일시 응답 타입 수정
  src/main/java/com/gamzabat/algohub/feature/comment/dto/GetCommentResponse.java
  src/main/java/com/gamzabat/algohub/feature/notification/dto/GetNotificationResponse.java
  src/test/java/com/gamzabat/algohub/feature/notice/service/NoticeCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionCommentServiceTest.java
Labels: refactoring

#377 fix: prevent solution submission failure for duplicate BJNickname users
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/main/java/com/gamzabat/algohub/feature/user/repository/UserRepository.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: bug

#375 fix: 알림 대상에서 자신 제외
  src/main/java/com/gamzabat/algohub/feature/group/ranking/service/RankingService.java
  src/main/java/com/gamzabat/algohub/feature/notification/service/NotificationService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionCommentService.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/feature/group/ranking/service/RankingServiceTest.java
  src/test/java/com/gamzabat/algohub/feature/solution/controller/SolutionControllerTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionCommentServiceTest.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: bug, self-merge
