Repository GAMZA-BAT/algohub-server, pull requests merged in 2025-01, with the labels that each got.

#259 feat : 그룹 삭제 보수공사
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/domain/StudyGroup.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/repository/GroupMemberRepository.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/repository/StudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/repository/querydsl/CustomStudyGroupRepository.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/repository/querydsl/CustomStudyGroupRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/notification/repository/querydsl/CustomNotificationSettingRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/problem/controller/ProblemController.java
  src/main/java/com/gamzabat/algohub/feature/problem/domain/Problem.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/querydsl/CustomProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/querydsl/CustomProblemRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
  src/main/java/com/gamzabat/algohub/feature/solution/domain/Solution.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/service/ProblemServiceTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: new-feature, refactoring

#263 feat: Send message to discord when the server get uncaught exceptions
  .github/workflows/deploy.yml
  .github/workflows/tests.yml
  build.gradle
  src/main/java/com/gamzabat/algohub/common/logging/DiscordLogAppender.java
  src/main/java/com/gamzabat/algohub/common/logging/MDCFilter.java
  src/main/java/com/gamzabat/algohub/common/logging/MDCUtil.java
  src/main/java/com/gamzabat/algohub/common/logging/RequestBodyWrapper.java
  src/main/java/com/gamzabat/algohub/common/logging/RequestWrappingFilter.java
  src/main/java/com/gamzabat/algohub/config/MDCFilterConfig.java
  src/main/resources/console-appender.xml
  src/main/resources/discord-appender.xml
  src/main/resources/logback-spring.xml
Labels: new-feature, trivial

#266 fix : 토큰 resolve 시 null 반환을 예외 throw로 수정
  src/main/java/com/gamzabat/algohub/common/jwt/TokenProvider.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: bug

#273 env: Enforce the server's timezone to be set as Asia/Seoul (KST)
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/gamzabat/algohub/AlgohubApplication.java
Labels: trivial

#274 fix : JwtFilter 예외 엔드포인트 추가
  src/main/java/com/gamzabat/algohub/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gamzabat/algohub/common/jwt/TokenProvider.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: bug, new-feature

#282 env : Enhance test output for detailed results during execution
  .github/workflows/tests.yml
Labels: trivial, test

#285 fix : refresh token 스케줄러 delete/update 쿼리 오류 해결
  src/main/java/com/gamzabat/algohub/common/jwt/TokenProvider.java
Labels: bug

#283 refactor: 부방장 초대코드 조회 가능 ..!
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
Labels: new-feature

#276 refactor: 닉네임 중복, 이메일형식 검증 추가
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/CheckEmailFormException.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/CheckPasswordFormException.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: refactoring

#281 feat : Github 소셜 로그인 추가
  build.gradle
  prepare-build.sh
  src/main/java/com/gamzabat/algohub/auth/controller/OAuth2Controller.java
  src/main/java/com/gamzabat/algohub/auth/dto/GithubEmailDto.java
  src/main/java/com/gamzabat/algohub/auth/dto/GithubUserDto.java
  src/main/java/com/gamzabat/algohub/auth/dto/OAuthAccessTokenDto.java
  src/main/java/com/gamzabat/algohub/auth/exception/GithubApiException.java
  src/main/java/com/gamzabat/algohub/auth/service/OAuth2Service.java
  src/main/java/com/gamzabat/algohub/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gamzabat/algohub/common/jwt/TokenProvider.java
  src/main/java/com/gamzabat/algohub/constants/ApiConstants.java
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/user/domain/User.java
  src/main/resources/application.yml
Labels: new-feature

#295 refactor : 그룹 role 조회 response 타입 수정
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/GroupRoleResponse.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: bug, refactoring

#297 feat: 코드로 그룹 참여시 아이디 반환
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/controller/StudyGroupController.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/GetGroupIdResponse.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
Labels: enhancement, new-feature

#301 refactor : 닉네임 검증 시 한글 제한 추가
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: refactoring

#299 fix : 문제 관련 알림 전송 no session 에러 해결
  src/main/java/com/gamzabat/algohub/feature/problem/service/ProblemService.java
Labels: bug

#306 refactor:필터링 언어 목록 수정
  src/main/java/com/gamzabat/algohub/constants/LanguageConstants.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/querydsl/CustomSolutionRepositoryImpl.java
Labels: refactoring

#304 refactor: 이미지 수정 리팩토링
  build.gradle
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/EditGroupRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/image/service/ImageService.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/UpdateUserRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/aws-appender.xml
  src/test/java/com/gamzabat/algohub/feature/studygroup/controller/StudyGroupControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
  src/test/java/com/gamzabat/algohub/service/StudyGroupServiceTest.java
Labels: refactoring

#310 refactor:RequestException추가하기
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
Labels: refactoring

#317 fix : skip jwt exists checking for add solution api
  src/main/java/com/gamzabat/algohub/common/jwt/JwtAuthenticationFilter.java
Labels: bug

#312 env : 에러 로그 웹훅 수정
  src/main/java/com/gamzabat/algohub/common/logging/DiscordLogAppender.java
Labels: trivial

#314 refactor: 수정 API 리팩토링
  src/main/java/com/gamzabat/algohub/feature/comment/dto/UpdateCommentRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/domain/StudyGroup.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/dto/EditGroupRequest.java
  src/main/java/com/gamzabat/algohub/feature/group/studygroup/service/StudyGroupService.java
  src/main/java/com/gamzabat/algohub/feature/notice/domain/Notice.java
  src/main/java/com/gamzabat/algohub/feature/notice/service/NoticeService.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
Labels: refactoring
