Repository GAMZA-BAT/algohub-server, pull requests merged in 2025-05, with the labels that each got.

#379 feat: 풀이 현황 테이블 조회 API 추가
  src/main/java/com/gamzabat/algohub/feature/problem/repository/querydsl/CustomProblemRepository.java
  src/main/java/com/gamzabat/algohub/feature/problem/repository/querydsl/CustomProblemRepositoryImpl.java
  src/main/java/com/gamzabat/algohub/feature/solution/controller/SolutionController.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetCurrentSolvingStatusResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/dto/GetSolvingStatusPerProblemResponse.java
  src/main/java/com/gamzabat/algohub/feature/solution/repository/SolutionRepository.java
  src/main/java/com/gamzabat/algohub/feature/solution/service/SolutionService.java
  src/test/java/com/gamzabat/algohub/service/SolutionServiceTest.java
Labels: new-feature

#382 refactor: ranking count query 수정
  src/main/java/com/gamzabat/algohub/feature/group/ranking/repository/querydsl/CustomRankingRepositoryImpl.java
Labels: refactoring

#384 fix: 문제 마감 날짜 풀이 등록 시 오류 해결
  src/main/java/com/gamzabat/algohub/feature/problem/repository/ProblemRepository.java
Labels: bug
