Repository GAMZA-BAT/algohub-server, pull requests merged in 2025-03, with the labels that each got.

#350 feat: Add unique id on log per thread
  src/main/java/com/gamzabat/algohub/common/logging/DiscordLogAppender.java
  src/main/java/com/gamzabat/algohub/common/logging/MDCFilter.java
  src/main/java/com/gamzabat/algohub/common/logging/MDCUtil.java
  src/main/resources/console-appender.xml
Labels: new-feature

#347 refactor:회원가입시 백준ID 입력 제거 및 백준ID 연결 API 따로 분리
  build.gradle
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/RegisterBjNickNameRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/RegisterRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: refactoring

#348 feat : 이메일 유효성 검증 API
  src/main/java/com/gamzabat/algohub/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gamzabat/algohub/common/redis/RedisService.java
  src/main/java/com/gamzabat/algohub/constants/EmailTemplateStrings.java
  src/main/java/com/gamzabat/algohub/enums/EmailType.java
  src/main/java/com/gamzabat/algohub/exception/CustomExceptionHandler.java
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/RegisterRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/dto/SendVerificationCodeRequest.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/CannotFoundVerificationCodeException.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/InvalidEmailException.java
  src/main/java/com/gamzabat/algohub/feature/user/exception/InvalidVerificationCodeException.java
  src/main/java/com/gamzabat/algohub/feature/user/service/EmailService.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/main/resources/templates/email-template.html
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: new-feature

#356 chore : Github OAuth env 분리
  prepare-build.sh
  src/main/resources/application.yml
Labels: trivial

#355 feat:백준ID 삭제 API 만들기
  src/main/java/com/gamzabat/algohub/feature/user/controller/UserController.java
  src/main/java/com/gamzabat/algohub/feature/user/service/UserService.java
  src/test/java/com/gamzabat/algohub/feature/user/controller/UserControllerTest.java
  src/test/java/com/gamzabat/algohub/feature/user/service/UserServiceTest.java
Labels: new-feature
